version: '3'

services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/volume/:/var/lib/postgresql/data
